"""catalog tables

Revision ID: 940f61d616da
Revises: 21ffcd8debb4
Create Date: 2026-07-19 05:05:44.527870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940f61d616da'
down_revision: Union[str, None] = '21ffcd8debb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_roles_id'), 'catalog_roles', ['id'], unique=False)
    op.create_index(op.f('ix_catalog_roles_slug'), 'catalog_roles', ['slug'], unique=True)
    op.create_table('catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['catalog_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_items_category'), 'catalog_items', ['category'], unique=False)
    op.create_index(op.f('ix_catalog_items_id'), 'catalog_items', ['id'], unique=False)
    op.create_index(op.f('ix_catalog_items_role_id'), 'catalog_items', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_items_role_id'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_id'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_category'), table_name='catalog_items')
    op.drop_table('catalog_items')
    op.drop_index(op.f('ix_catalog_roles_slug'), table_name='catalog_roles')
    op.drop_index(op.f('ix_catalog_roles_id'), table_name='catalog_roles')
    op.drop_table('catalog_roles')
    # ### end Alembic commands ###
